-- =============================================================================
-- AI Mirror Platform — reference schema
-- -----------------------------------------------------------------------------
-- This file is a GENERATED REFERENCE. The source of truth is the Alembic
-- migrations under backend/alembic/versions. Regenerate after a migration with:
--
--   cd backend && alembic upgrade head \
--     && pg_dump --schema-only --no-owner "$DATABASE_URL" > ../database/schema.sql
--
-- All ids are UUID (UUIDv7, time-ordered, generated by the application). All
-- tables carry created_at/updated_at; user-facing entities use soft-delete.
-- =============================================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ---- Roles & users --------------------------------------------------------
CREATE TABLE roles (
    id          UUID PRIMARY KEY,
    name        VARCHAR(32) UNIQUE NOT NULL,
    description VARCHAR(255),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE users (
    id                UUID PRIMARY KEY,
    email             VARCHAR(320) UNIQUE NOT NULL,
    password_hash     VARCHAR(255),
    email_verified_at TIMESTAMPTZ,
    display_name      VARCHAR(120),
    avatar_image_id   UUID,
    locale            VARCHAR(16) NOT NULL DEFAULT 'en',
    status            VARCHAR(16) NOT NULL DEFAULT 'active',  -- active|suspended|deleted
    settings_json     JSONB NOT NULL DEFAULT '{}',
    deleted_at        TIMESTAMPTZ,
    purge_after       TIMESTAMPTZ,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uq_users_email_lower ON users (lower(email));

CREATE TABLE user_roles (
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role_id UUID NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE oauth_identities (
    id               UUID PRIMARY KEY,
    user_id          UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    provider         VARCHAR(32) NOT NULL,
    provider_subject VARCHAR(255) NOT NULL,
    linked_at        TIMESTAMPTZ,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_oauth_provider_subject UNIQUE (provider, provider_subject)
);

CREATE TABLE sessions (
    id                 UUID PRIMARY KEY,
    user_id            UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    refresh_token_hash VARCHAR(64) UNIQUE NOT NULL,
    family_id          UUID NOT NULL,
    user_agent         VARCHAR(512),
    ip                 INET,
    expires_at         TIMESTAMPTZ NOT NULL,
    revoked_at         TIMESTAMPTZ,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_sessions_user ON sessions(user_id);
CREATE INDEX ix_sessions_family ON sessions(family_id);

CREATE TABLE consents (
    id         UUID PRIMARY KEY,
    user_id    UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    type       VARCHAR(32) NOT NULL,
    version    VARCHAR(32) NOT NULL,
    granted_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE verification_tokens (
    id         UUID PRIMARY KEY,
    user_id    UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    purpose    VARCHAR(32) NOT NULL,             -- verify_email|reset
    token_hash VARCHAR(64) UNIQUE NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    used_at    TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE data_exports (
    id           UUID PRIMARY KEY,
    user_id      UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    status       VARCHAR(16) NOT NULL DEFAULT 'pending',
    object_key   VARCHAR(512),
    completed_at TIMESTAMPTZ,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---- Styles ---------------------------------------------------------------
CREATE TABLE styles (
    id               UUID PRIMARY KEY,
    slug             VARCHAR(64) UNIQUE NOT NULL,
    name             VARCHAR(120) NOT NULL,
    category         VARCHAR(64) NOT NULL DEFAULT 'general',
    description      VARCHAR(512),
    template         VARCHAR(2000) NOT NULL DEFAULT '{prompt}',
    negative_prompt  VARCHAR(2000),
    model_ref        VARCHAR(128) NOT NULL DEFAULT 'flux.1',
    lora_refs        JSONB NOT NULL DEFAULT '[]',
    default_params   JSONB NOT NULL DEFAULT '{}',
    cost_multiplier  NUMERIC(6,2) NOT NULL DEFAULT 1,
    plan_gate        VARCHAR(32),
    is_active        BOOLEAN NOT NULL DEFAULT true,
    preview_image_id UUID,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---- Images ---------------------------------------------------------------
CREATE TABLE images (
    id            UUID PRIMARY KEY,
    user_id       UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    kind          VARCHAR(16) NOT NULL,            -- upload|generation
    bucket        VARCHAR(64) NOT NULL,
    object_key    VARCHAR(512) NOT NULL,
    mime          VARCHAR(64) NOT NULL,
    width         INTEGER,
    height        INTEGER,
    bytes         BIGINT,
    content_hash  VARCHAR(64),
    safety_status VARCHAR(16) NOT NULL DEFAULT 'pending',
    visibility    VARCHAR(16) NOT NULL DEFAULT 'private',
    share_token   VARCHAR(64) UNIQUE,
    is_favorite   BOOLEAN NOT NULL DEFAULT false,
    job_id        UUID,
    meta          JSONB NOT NULL DEFAULT '{}',
    deleted_at    TIMESTAMPTZ,
    purge_after   TIMESTAMPTZ,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_images_user_created ON images(user_id, created_at);
CREATE INDEX ix_images_content_hash ON images(content_hash);
CREATE INDEX ix_images_share_token ON images(share_token);

-- ---- Credit ledger --------------------------------------------------------
CREATE TABLE credit_balances (
    user_id    UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    balance    BIGINT NOT NULL DEFAULT 0,
    held       BIGINT NOT NULL DEFAULT 0,
    version    INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_balance_non_negative CHECK (balance >= 0)
);

CREATE TABLE credit_transactions (
    id              UUID PRIMARY KEY,
    user_id         UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    type            VARCHAR(16) NOT NULL,           -- grant|hold|debit|refund|reversal
    amount          BIGINT NOT NULL,                -- signed; balance = sum(amount)
    job_id          VARCHAR(36),
    payment_id      VARCHAR(36),
    idempotency_key VARCHAR(160),
    expires_at      TIMESTAMPTZ,
    reason          VARCHAR(255),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_credit_txn_user_created ON credit_transactions(user_id, created_at);
CREATE UNIQUE INDEX uq_credit_txn_idem ON credit_transactions(user_id, idempotency_key);

-- ---- Jobs -----------------------------------------------------------------
CREATE TABLE jobs (
    id                  UUID PRIMARY KEY,
    user_id             UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    idempotency_key     VARCHAR(128) UNIQUE NOT NULL,
    style_id            UUID REFERENCES styles(id) ON DELETE SET NULL,
    status              VARCHAR(16) NOT NULL DEFAULT 'queued',
    cost_credits        INTEGER NOT NULL DEFAULT 0,
    hold_txn_id         UUID REFERENCES credit_transactions(id) ON DELETE SET NULL,
    prompt              VARCHAR(4000) NOT NULL DEFAULT '',
    negative_prompt     VARCHAR(4000),
    seed                INTEGER,
    params              JSONB NOT NULL DEFAULT '{}',
    stages              JSONB NOT NULL DEFAULT '[]',
    reference_image_ids JSONB NOT NULL DEFAULT '[]',
    progress            INTEGER NOT NULL DEFAULT 0,
    priority            INTEGER NOT NULL DEFAULT 1,
    attempts            INTEGER NOT NULL DEFAULT 0,
    error_stage         VARCHAR(32),
    error_code          VARCHAR(64),
    error_message       VARCHAR(512),
    requeued_from       UUID REFERENCES jobs(id) ON DELETE SET NULL,
    started_at          TIMESTAMPTZ,
    finished_at         TIMESTAMPTZ,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_jobs_user_created ON jobs(user_id, created_at);
CREATE INDEX ix_jobs_status ON jobs(status);

CREATE TABLE job_results (
    id         UUID PRIMARY KEY,
    job_id     UUID NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
    image_id   UUID NOT NULL REFERENCES images(id) ON DELETE CASCADE,
    stage      VARCHAR(32) NOT NULL,
    is_primary BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_job_results_job ON job_results(job_id);

-- ---- Plans / subscriptions / payments -------------------------------------
CREATE TABLE plans (
    id                UUID PRIMARY KEY,
    slug              VARCHAR(64) UNIQUE NOT NULL,
    name              VARCHAR(120) NOT NULL,
    kind              VARCHAR(16) NOT NULL DEFAULT 'subscription',
    monthly_credits   INTEGER NOT NULL DEFAULT 0,
    credits           INTEGER NOT NULL DEFAULT 0,
    price_cents       INTEGER NOT NULL,
    currency          VARCHAR(3) NOT NULL DEFAULT 'USD',
    provider_price_id VARCHAR(128),
    features          JSONB NOT NULL DEFAULT '{}',
    is_active         BOOLEAN NOT NULL DEFAULT true,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE subscriptions (
    id                       UUID PRIMARY KEY,
    user_id                  UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    plan_id                  UUID NOT NULL REFERENCES plans(id) ON DELETE RESTRICT,
    provider_subscription_id VARCHAR(128),
    status                   VARCHAR(32) NOT NULL DEFAULT 'active',
    current_period_end       TIMESTAMPTZ,
    cancel_at                TIMESTAMPTZ,
    created_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_subscriptions_user ON subscriptions(user_id);

CREATE TABLE payments (
    id                  UUID PRIMARY KEY,
    user_id             UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    provider            VARCHAR(32) NOT NULL DEFAULT 'stripe',
    provider_event_id   VARCHAR(255) UNIQUE NOT NULL,    -- idempotency
    provider_session_id VARCHAR(255),
    kind                VARCHAR(16) NOT NULL DEFAULT 'purchase',
    plan_id             UUID REFERENCES plans(id) ON DELETE SET NULL,
    amount_cents        INTEGER NOT NULL DEFAULT 0,
    currency            VARCHAR(3) NOT NULL DEFAULT 'USD',
    credits_granted     INTEGER NOT NULL DEFAULT 0,
    status              VARCHAR(32) NOT NULL DEFAULT 'succeeded',
    invoice_object_key  VARCHAR(512),
    related_payment_id  UUID REFERENCES payments(id) ON DELETE SET NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_payments_user ON payments(user_id);
CREATE INDEX ix_payments_event ON payments(provider_event_id);

-- ---- Moderation / flags / audit -------------------------------------------
CREATE TABLE moderation_events (
    id           UUID PRIMARY KEY,
    subject_type VARCHAR(16) NOT NULL,             -- upload|prompt|output
    subject_id   VARCHAR(64),
    user_id      UUID REFERENCES users(id) ON DELETE SET NULL,
    classifier   VARCHAR(64) NOT NULL,
    score        NUMERIC(5,4),
    decision     VARCHAR(16) NOT NULL DEFAULT 'pending',
    detail       VARCHAR(512),
    moderator_id UUID REFERENCES users(id) ON DELETE SET NULL,
    decided_at   TIMESTAMPTZ,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_moderation_decision ON moderation_events(decision);

CREATE TABLE feature_flags (
    key         VARCHAR(64) PRIMARY KEY,
    value       JSONB NOT NULL DEFAULT '{}',
    description VARCHAR(255),
    updated_by  UUID REFERENCES users(id) ON DELETE SET NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE audit_log (
    id            UUID PRIMARY KEY,
    actor_id      UUID REFERENCES users(id) ON DELETE SET NULL,
    action        VARCHAR(64) NOT NULL,
    target_type   VARCHAR(32),
    target_id     VARCHAR(64),
    metadata_json JSONB NOT NULL DEFAULT '{}',
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_audit_actor_created ON audit_log(actor_id, created_at);
